import { workKey } from "./identity";
export interface Candidate {workKey:string;editionKey:string;title:string;author:string;year:number|null;isbn13:string|null;language:string;coverUrl:string|null;sourceUrl:string;sourceLabel:string;subjects:string[];category:"strong fit"|"discovery"|"wildcard";why:string;caveat:string;ratings:{goodreads:{rating:number|null;count:number|null;status:string;url:string;freshness:string};amazon:{rating:number|null;count:number|null;status:string;url:string;freshness:string}};}
interface OpenLibraryDoc {key:string;title:string;author_name?:string[];first_publish_year?:number;cover_i?:number;isbn?:string[];language?:string[];subject?:string[];ratings_average?:number;ratings_count?:number;}
export function rankCandidates(docs:OpenLibraryDoc[],known:Set<string>,dismissed:Set<string>,positiveTitles:string[],mood:string,negativeSignals:string[]=[]):Candidate[]{
  const negative=new Set(negativeSignals.map(x=>x.toLowerCase()));const penalty=(d:OpenLibraryDoc)=>(d.subject||[]).slice(0,10).filter(s=>negative.has(s.toLowerCase())).length;const ordered=[...docs].sort((a,b)=>penalty(a)-penalty(b));
  const seenAuthors=new Set<string>();const candidates:Candidate[]=[];
  for(const d of ordered){const author=d.author_name?.[0]||"Unknown author";const wk=workKey(d.title,author);if(known.has(wk)||dismissed.has(wk)||seenAuthors.has(author.toLowerCase()))continue;const isbn13=d.isbn?.find(x=>/^\d{13}$/.test(x))||null;const subjects=(d.subject||[]).slice(0,5);const idx=candidates.length;const category=idx<3?"strong fit":idx<6?"discovery":"wildcard";const anchor=positiveTitles[idx%Math.max(positiveTitles.length,1)];const overlap=subjects[0]?.toLowerCase();const why=anchor?`Selected from a real catalog because its ${overlap||"subject"} metadata connects with your high rating for ${anchor}${mood?`, while fitting your current “${mood}” mood`:""}.`:`A catalog-grounded ${overlap||"literary"} candidate${mood?` matching your current “${mood}” mood`:""}; more history will sharpen the fit.`;const caveat=penalty(d)>0?`Catalog subjects overlap ${penalty(d)} signal(s) from lower-rated history; this is a deliberate stretch.`:subjects.length<2?"Catalog evidence is thin, so treat this as an exploratory pick.":category==="wildcard"?"This deliberately sits outside your most common shelves.":"The fit is inferred from catalog subjects, not a promise that its tone will match.";
    candidates.push({workKey:wk,editionKey:isbn13||d.key,title:d.title,author,year:d.first_publish_year||null,isbn13,language:d.language?.includes("eng")?"eng":d.language?.[0]||"und",coverUrl:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`:null,sourceUrl:`https://openlibrary.org${d.key}`,sourceLabel:"Open Library catalog",subjects,category,why,caveat,ratings:{goodreads:{rating:null,count:null,status:"not_retrieved",url:`https://www.goodreads.com/search?q=${encodeURIComponent(`${d.title} ${author}`)}`,freshness:"Unknown"},amazon:{rating:null,count:null,status:"not_retrieved",url:`https://www.amazon.com/s?k=${encodeURIComponent(isbn13||`${d.title} ${author}`)}&i=stripbooks`,freshness:"Unknown"}}});seenAuthors.add(author.toLowerCase());if(candidates.length>=9)break;
  }return candidates;
}
export async function discoverOpenLibrary(query:string){const url=new URL("https://openlibrary.org/search.json");url.searchParams.set("q",query);url.searchParams.set("language","eng");url.searchParams.set("fields","key,title,author_name,first_publish_year,cover_i,isbn,language,subject,ratings_average,ratings_count");url.searchParams.set("limit","50");const r=await fetch(url,{headers:{"User-Agent":"ShelfScout/0.1 (self-hosted personal companion)"},signal:AbortSignal.timeout(12_000),next:{revalidate:3600}});if(!r.ok)throw new Error(`Open Library ${r.status}`);return (await r.json() as {docs:OpenLibraryDoc[]}).docs;}
