import { describe,expect,it } from "vitest";
import { parseGoodreadsCsv,importGoodreadsRows } from "../src/lib/goodreads";
import { createDatabase } from "../src/lib/db";

const csv='\uFEFFBook Id,Title,Author,ISBN,ISBN13,My Rating,Average Rating,Bookshelves,Exclusive Shelf,Date Read,My Review,Read Count,Mystery Column\n42,"A Title, With Comma",Zoë Author,"=""0306406152""","=""9780306406157""",0,4.2,"quiet, sci-fi",dnf,2020-05-03,"Line one\nLine two",2,keep me\n,"Nameless ID",Somebody,broken,broken,5,,favourite,read,,,1,x\n';
describe("Goodreads CSV",()=>{
 it("handles BOM, quoted commas, multiline Unicode, wrappers, unrated zero and raw columns",()=>{const {headers,rows}=parseGoodreadsCsv(csv);expect(headers).toContain("Mystery Column");expect(rows[0]).toMatchObject({sourceId:"42",title:"A Title, With Comma",author:"Zoë Author",isbnOriginal:'="0306406152"',isbn:"0306406152",isbn13:"9780306406157",isbnValid:true,personalRating:null,exclusiveStatus:"dnf",datePrecision:"day",readCount:2});expect(rows[0].review).toBe("Line one\nLine two");expect(rows[0].shelves).toEqual(["quiet","sci-fi"]);expect(rows[0].raw["Mystery Column"]).toBe("keep me");expect(rows[1].sourceId).toBeNull();expect(rows[1].isbnValid).toBe(false);});
 it("accounts exactly and reimports idempotently without losing feedback or duplicating rating snapshots",()=>{const db=createDatabase(":memory:");db.prepare("INSERT INTO imports(id,filename,stored_path,sha256,headers_json,preview_json,status,row_count,created_at) VALUES('i','x','x','x','[]','{}','previewed',2,'now')").run();const rows=parseGoodreadsCsv(csv).rows;const first=importGoodreadsRows(db,"i",rows);expect(first.total).toBe(first.imported+first.updated+first.unchanged+first.rejected);expect(first).toMatchObject({imported:2,missingIds:1});expect(db.prepare("SELECT source,rating,retrieval_status FROM ratings").get()).toEqual({source:"goodreads-import",rating:4.2,retrieval_status:"import_snapshot"});db.prepare("UPDATE reading_records SET companion_updated_at='later'").run();db.prepare("INSERT INTO imports(id,filename,stored_path,sha256,headers_json,preview_json,status,row_count,created_at) VALUES('i2','x','x','x','[]','{}','previewed',2,'now')").run();const second=importGoodreadsRows(db,"i2",rows);expect(second.unchanged).toBe(2);expect(db.prepare("SELECT companion_updated_at FROM reading_records LIMIT 1").get()).toEqual({companion_updated_at:"later"});expect(db.prepare("SELECT count(*) count FROM ratings").get()).toEqual({count:1});db.close();});
});
