import { randomUUID } from "node:crypto";
import { getDb } from "../src/lib/db";
import { BookOrbitClient } from "../src/lib/bookorbit";
import { normalizeStatus } from "../src/lib/acquisition";
import { normalize } from "../src/lib/identity";

const db=getDb();let stopping=false;process.on("SIGTERM",()=>{stopping=true});process.on("SIGINT",()=>{stopping=true});
type Job={id:string;payload_json:string;attempts:number};
function claim():Job|undefined{const now=new Date().toISOString();return db.transaction(()=>{const job=db.prepare("SELECT id,payload_json,attempts FROM jobs WHERE status='queued' AND run_after<=? ORDER BY run_after LIMIT 1").get(now) as Job|undefined;if(job)db.prepare("UPDATE jobs SET status='running',locked_at=?,attempts=attempts+1,updated_at=? WHERE id=?").run(now,now,job.id);return job;})();}
function event(id:string,status:string,detail:string){db.prepare("INSERT INTO acquisition_events(acquisition_id,status,detail,created_at) VALUES(?,?,?,?)").run(id,status,detail,new Date().toISOString());}
async function reconcile(id:string){const row=db.prepare("SELECT * FROM acquisitions WHERE id=?").get(id) as Record<string,unknown>|undefined;if(!row)return;const bo=new BookOrbitClient();let upstream:Record<string,unknown>|null=row.upstream_request_id?await bo.requestStatus(String(row.upstream_request_id)):row.upstream_book_id?{status:"available",matchedBookId:Number(row.upstream_book_id),source:"availability_check"}:null;
  if(!upstream){const availability=await bo.availability({title:String(row.title),author:row.author?String(row.author):null,isbn13:row.isbn13?String(row.isbn13):null,language:String(row.language)});if(availability.ownedBookId){db.prepare("UPDATE acquisitions SET upstream_book_id=? WHERE id=?").run(String(availability.ownedBookId),id);upstream={status:"available",matchedBookId:availability.ownedBookId,source:"uncertain_submission_reconciliation"};}else if(availability.existingRequestId){db.prepare("UPDATE acquisitions SET upstream_request_id=? WHERE id=?").run(String(availability.existingRequestId),id);upstream=await bo.requestStatus(availability.existingRequestId);}else{const detail="BookOrbit availability confirmed no owned book or existing request after the uncertain submission; a new explicit Get book action is safe.";db.prepare("UPDATE acquisitions SET status='failed',last_error=?,updated_at=? WHERE id=?").run(detail,new Date().toISOString(),id);event(id,"failed",detail);return;}}
  const download=upstream.download as Record<string,unknown>|undefined;let status=normalizeStatus(String(upstream.status||"pending"),download?String(download.status||""):null);let detail=`BookOrbit: ${String(upstream.status||"unknown")}`;
  if(status==="available_in_bookorbit"){
    const bookId=upstream.matchedBookId;if(!bookId){status="needs_attention";detail="BookOrbit marked available without a matched book ID";}else{const book=await bo.book(String(bookId));const files=Array.isArray(book.files)?book.files as Record<string,unknown>[]:[];const epub=files.some(f=>String(f.extension||f.format||"").toLowerCase().includes("epub")||String(f.fileName||"").toLowerCase().endsWith(".epub"));const titleMatch=normalize(String(book.title||""))===normalize(String(row.title));const expectedAuthor=normalize(String(row.author||""));const authors=Array.isArray(book.authors)?book.authors.map(a=>normalize(typeof a==="string"?a:String((a as Record<string,unknown>).name||""))):[];const authorMatch=!expectedAuthor||authors.some(a=>a===expectedAuthor);const language=normalize(String(book.language||book.languages||""));const languageMatch=!row.language||row.language==="und"||!language||language.includes(normalize(String(row.language)));
      if(!titleMatch||!authorMatch||!languageMatch||!epub){status="needs_attention";detail=`Import needs review: title=${titleMatch}, author=${authorMatch}, language=${languageMatch}, EPUB=${epub}`;}else if(row.target_collection_id){await bo.addToCollection(String(row.target_collection_id),String(bookId));const membership=await bo.collectionBooks(String(row.target_collection_id));if(membership.items.some(x=>String(x.id)===String(bookId))){status="ready_for_kobo";detail="Imported EPUB verified and target Kobo-synced collection membership read back";}else{status="needs_attention";detail="Collection update was not confirmed on read-back";}}
      else{status="needs_attention";detail="Book is available; choose an existing Kobo-synced target collection";}db.prepare("UPDATE acquisitions SET upstream_book_id=? WHERE id=?").run(String(bookId),id);
    }
  }
  db.prepare("UPDATE acquisitions SET status=?,upstream_state_json=?,last_error=?,updated_at=? WHERE id=?").run(status,JSON.stringify(upstream),status==="needs_attention"?detail:null,new Date().toISOString(),id);event(id,status,detail);
  if(!["ready_for_kobo","failed","cancelled","needs_attention"].includes(status)){const now=new Date().toISOString();db.prepare("INSERT INTO jobs(id,type,payload_json,status,run_after,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(),"reconcile_acquisition",JSON.stringify({id}),"queued",new Date(Date.now()+30_000).toISOString(),now,now);}
}
async function tick(){const job=claim();if(!job)return false;try{const {id}=JSON.parse(job.payload_json) as {id:string};await reconcile(id);db.prepare("UPDATE jobs SET status='complete',updated_at=? WHERE id=?").run(new Date().toISOString(),job.id);}catch(error){const message=error instanceof Error?error.message:"worker error";const delay=Math.min(300_000,5000*2**job.attempts);db.prepare("UPDATE jobs SET status=?,run_after=?,last_error=?,locked_at=NULL,updated_at=? WHERE id=?").run(job.attempts>=8?"failed":"queued",new Date(Date.now()+delay).toISOString(),message,new Date().toISOString(),job.id);}return true;}
// Recover jobs left running by a terminated worker.
db.prepare("UPDATE jobs SET status='queued',locked_at=NULL,run_after=? WHERE status='running' AND locked_at<?").run(new Date().toISOString(),new Date(Date.now()-10*60_000).toISOString());
while(!stopping){if(!await tick())await new Promise(r=>setTimeout(r,1000));}
