'use client';
import { useEffect, useState } from 'react';
import { readingLanguages } from '@/src/lib/languages';
import { settingsRequest } from './settings-request';
import type { Profile, Preference, TasteSettings } from '@/src/lib/recommendation/types';
export function TasteEditor() {
    const [saving, setSaving] = useState(false);
    const [profile, setProfile] = useState<Profile | null>(null), [models, setModels] = useState<Preference[]>([]), [message, setMessage] = useState(''), [value, setValue] = useState(''), [direction, setDirection] = useState<'prefer' | 'avoid'>('prefer'), [dimension, setDimension] = useState<Preference['dimension']>('theme');
    useEffect(() => { void fetch('/api/taste').then(r => r.json()).then(d => { setProfile(d.profile); setModels(d.lastModelPreferences || []); }).catch(() => setMessage('Could not load taste profile.')); }, []);
    async function save(settings: TasteSettings) {
        if (!profile || saving) return;
        const previous = profile;
        setSaving(true); setProfile({ ...profile, settings }); setMessage('Saving…');
        try {
            const { token } = await settingsRequest('/api/auth/csrf');
            const data = await settingsRequest('/api/taste', { method: 'PUT', headers: { 'Content-Type': 'application/json', 'x-csrf-token': token }, body: JSON.stringify(settings) });
            setProfile(data.profile); setMessage('Saved. Regenerate suggestions to apply these preferences.');
        } catch (error) {
            setProfile(previous); setMessage(error instanceof Error ? error.message : 'Could not save your preferences.');
        } finally { setSaving(false); }
    }
    if (!profile)
        return <article><h3>Taste profile</h3><p>{message || 'Loading evidence…'}</p></article>;
    return <article className="taste-editor"><h3>Your taste, with evidence</h3><p>Explicit preferences override matching inferences. Missing traits remain unknown. Suggested moods focus a single batch. Series are recommended from book one.</p><p role="status">{message}</p><fieldset className="taste-controls" disabled={saving}><fieldset className="language-settings"><legend>Reading languages</legend><p>Choose at least one language. Recommendations must list an edition in one of your selected languages; books with unknown language metadata are hidden. New profiles start with English.</p><div className="language-options">{readingLanguages.slice(0, 6).map(language => <label key={language.code}><input type="checkbox" checked={profile.settings.languages.includes(language.code)} disabled={profile.settings.languages.length === 1 && profile.settings.languages.includes(language.code)} onChange={event => void save({ ...profile.settings, languages: event.target.checked ? [...profile.settings.languages, language.code] : profile.settings.languages.filter(code => code !== language.code) })}/>{language.label}</label>)}</div><details><summary>More languages</summary><div className="language-options">{readingLanguages.slice(6).map(language => <label key={language.code}><input type="checkbox" checked={profile.settings.languages.includes(language.code)} disabled={profile.settings.languages.length === 1 && profile.settings.languages.includes(language.code)} onChange={event => void save({ ...profile.settings, languages: event.target.checked ? [...profile.settings.languages, language.code] : profile.settings.languages.filter(code => code !== language.code) })}/>{language.label}</label>)}</div></details><p>Selected: {profile.settings.languages.map(code => readingLanguages.find(language => language.code === code)?.label).join(', ')}. Changes filter existing picks immediately; regenerate suggestions for new matches.</p></fieldset><form onSubmit={e => { e.preventDefault(); if (value.trim()) {
        void save({ ...profile.settings, preferences: [...profile.settings.preferences.filter(p => p.value.toLowerCase() !== value.trim().toLowerCase()), { id: `owner:${Date.now()}`, dimension, value: value.trim(), direction, origin: 'explicit', confidence: 'supported', support: ['owner'], counterexamples: [] }] });
        setValue('');
    } }}><label>Dimension<select value={dimension} onChange={e => setDimension(e.target.value as Preference['dimension'])}>{['theme', 'prose', 'pacing', 'character', 'tone', 'structure', 'length', 'ambiguity', 'subject', 'author'].map(d => <option key={d}>{d}</option>)}</select></label><label>Preference<select value={direction} onChange={e => setDirection(e.target.value as 'prefer' | 'avoid')}><option value="prefer">Prefer</option><option value="avoid">Avoid</option></select></label><input aria-label="Preference description" placeholder="e.g. unreliable narrators" maxLength={120} value={value} onChange={e => setValue(e.target.value)} required/><button>Add preference</button></form><label><input type="checkbox" checked={profile.settings.includeReviews} onChange={e => void save({ ...profile.settings, includeReviews: e.target.checked })}/> Allow bounded review excerpts to be sent to my configured model. Titles, ratings, shelves and feedback reasons are sent when AI is enabled.</label><label><input type="checkbox" checked={profile.settings.rereads} onChange={e => void save({ ...profile.settings, rereads: e.target.checked })}/> Allow intentional rereads in future batches</label>
<label><input type="checkbox" checked={profile.settings.allowSeries} onChange={e => void save({ ...profile.settings, allowSeries: e.target.checked })}/> Allow books that are part of a series</label><p>When enabled, known series start at book one. When disabled, known series books are excluded. Catalog series coverage can be incomplete.</p>
 {[...profile.preferences, ...models.filter(p => !profile.settings.disabled.includes(p.id) && !profile.preferences.some(x => x.value === p.value))].map(p => <section key={p.id}><strong>{p.direction} {p.value}</strong><p>{p.dimension} · {p.origin} · {p.confidence}</p><details><summary>Supporting records and counterexamples</summary>{[...p.support, ...p.counterexamples].map(id => { const e = profile.evidence.find(e => e.id === id); return <p key={id}>{p.counterexamples.includes(id) ? 'Counterexample: ' : ''}{e ? `${e.title} — ${e.rating ?? 'unrated'} (${e.status})` : id}</p>; })}</details>{p.origin !== 'explicit' && <button onClick={() => void save({ ...profile.settings, preferences: [...profile.settings.preferences, { ...p, origin: 'explicit' }] })}>Confirm</button>}<button onClick={() => void save({ ...profile.settings, preferences: profile.settings.preferences.filter(x => x.id !== p.id), disabled: p.origin === 'explicit' ? profile.settings.disabled : [...profile.settings.disabled, p.id] })}>{p.origin === 'explicit' ? 'Remove' : 'Reject inference'}</button></section>)}{profile.settings.disabled.length > 0 && <button onClick={() => void save({ ...profile.settings, disabled: [] })}>Restore rejected inferences</button>}<p>{profile.unknown.join(' ')}</p></fieldset></article>;
}
export function FeedbackLog({onSelect}:{onSelect:(candidate:Record<string,unknown>)=>void}) { const [items, setItems] = useState<{
    id: number;
    work_key: string;
    action: string;
    reason: string;
    candidate_json: string;
}[]>([]), [notice, setNotice] = useState(''); async function load() { const r = await fetch('/api/feedback'); if (r.ok)
    setItems((await r.json()).items); } useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, []); async function change(id: number) { const token = (await (await fetch('/api/auth/csrf')).json()).token; const r = await fetch('/api/feedback', { method: 'DELETE', headers: { 'Content-Type': 'application/json', 'x-csrf-token': token }, body: JSON.stringify({ id }) }); if (r.ok) {
    await load();
    setNotice('Undone. Regenerate suggestions to reconsider this book.');
}
else
    setNotice('Undo failed.'); } async function rate(workKey: string, rating: string) { const token = (await (await fetch('/api/auth/csrf')).json()).token; const r = await fetch('/api/ratings', { method: 'PUT', headers: { 'Content-Type': 'application/json', 'x-csrf-token': token }, body: JSON.stringify({ workKey, rating: rating ? Number(rating) : null }) }); setNotice(r.ok ? 'Rating saved; it will inform the next profile.' : 'Rating could not be saved.'); } return <article><h3>Saved books and feedback</h3><p role="status">{notice}</p>{items.map(f => <section key={f.id}><strong>{JSON.parse(f.candidate_json || '{}').title || 'Book'} · {f.action.replaceAll('_', ' ')}</strong><p>{f.reason}</p><button onClick={()=>onSelect(JSON.parse(f.candidate_json||"{}"))}>View book</button><button onClick={() => void change(f.id)}>Undo</button><label>Subsequent rating<select defaultValue="" onChange={e => void rate(f.work_key, e.target.value)}><option value="">Unrated / clear override</option>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n} stars</option>)}</select></label></section>)}</article>; }

export function IdentityReview(){const[items,setItems]=useState<{catalog_key:string;title:string;options:{work_key:string;title:string;author:string}[]}[]>([]),[message,setMessage]=useState('');useEffect(()=>{void fetch('/api/identity').then(r=>r.json()).then(d=>setItems(d.items||[]));},[]);async function resolve(catalogKey:string,workKey:string|null){const token=(await(await fetch('/api/auth/csrf')).json()).token;const r=await fetch('/api/identity',{method:'PUT',headers:{'Content-Type':'application/json','x-csrf-token':token},body:JSON.stringify({catalogKey,workKey})});if(r.ok){setItems(v=>v.filter(i=>i.catalog_key!==catalogKey));setMessage('Identity decision saved. Refresh to apply.');}else setMessage('Could not save identity decision.');}return <article><h3>Identity review</h3><p>{message||'Ambiguous ISBN matches are withheld from recommendations until reviewed.'}</p>{items.map(i=><section key={i.catalog_key}><a href={`https://openlibrary.org${i.catalog_key}`} target="_blank" rel="noreferrer">{i.title} ↗</a>{i.options.map(o=><button key={o.work_key} onClick={()=>void resolve(i.catalog_key,o.work_key)}>Same work as {o.title} — {o.author}</button>)}<button onClick={()=>void resolve(i.catalog_key,null)}>A different work from these records</button></section>)}</article>}
